name: roomie
description: "Rumie — swipe-to-match roommate finding app."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  http: ^1.2.2
  provider: ^6.1.2
  flutter_secure_storage: ^10.2.0
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.0
  image_picker: ^1.1.2
  dio: ^5.4.0
  json_annotation: ^4.9.0
  get_it: ^9.2.1
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  # Asset folders. Drop your PNG/SVG/JPG files into these directories
  # and they will be bundled with the app automatically.
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: BricolageGrotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque-500.ttf
          weight: 500
        - asset: assets/fonts/BricolageGrotesque-600.ttf
          weight: 600
        - asset: assets/fonts/BricolageGrotesque-700.ttf
          weight: 700
        - asset: assets/fonts/BricolageGrotesque-800.ttf
          weight: 800
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-400.ttf
          weight: 400
        - asset: assets/fonts/DMSans-500.ttf
          weight: 500
        - asset: assets/fonts/DMSans-600.ttf
          weight: 600
        - asset: assets/fonts/DMSans-700.ttf
          weight: 700
